# Generated by Django 6.0.5 on 2026-05-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.FloatField()),
                ('rate', models.FloatField()),
                ('years', models.FloatField()),
                ('frequency', models.IntegerField()),
                ('final_amount', models.FloatField()),
                ('interests', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
